# Generated by Django 4.2.2 on 2024-04-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlist", "0002_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="ip_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="playlist",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
